---
- name: set sshd_config template
  template:
    src: etc-ssh-sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: "sshd -t -f %s"
  notify:
    - restart ssh
  tags:
    - aspects_openssh
