---
# tasks file for aspects_openssh
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - aspects_openssh

- name: set sshd_config template
  template: src=etc-ssh-sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
    - restart ssh
  tags:
    - aspects_openssh