---

- name: RedHat - Install openssh packages with yum
  when:
    ansible_pkg_mgr == "yum" and
    item.value.state != "default" and
    item.value.state != "purged" and
    item.value.RedHat is defined
  yum:
    name: "{{ item.value.RedHat }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ aspects_openssh_packages }}"
  tags:
    - aspects_openssh
    - aspects_openssh_package_install
