---
# handlers file for aspects_openssh

- name: restart ssh
  service: name={{ aspects_openssh_service_name }} state=restarted enabled=yes

- name: start ssh
  service: name={{ aspects_openssh_service_name }} state=started enabled=yes

- name: stop ssh
  service: name={{ aspects_openssh_service_name }} state=stopped enabled=no